using Microsoft.CodeAnalysis;

namespace Ling.RemoteServices.Generators;

internal static class GeneratorUtilities
{
    private static readonly SymbolDisplayFormat FullyQualifiedNullableFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    /// <summary>
    /// Gets the version of the source generator assembly.
    /// </summary>
    public static string Version { get; } =
        typeof(GeneratorUtilities).Assembly.GetName().Version?.ToString()
        ?? "1.0.0.0";

    /// <summary>
    /// Creates a code builder initialized with the common generated-file header.
    /// </summary>
    /// <returns>A code builder containing version, warning, and nullable directives.</returns>
    public static CodeBuilder CreateGeneratedCodeBuilder()
    {
        return new CodeBuilder()
            .AppendLine("// <auto-generated/>")
            .Append("// Generated by Ling.RemoteServices v")
            .Append(Version)
            .AppendLine(".")
            .AppendLine()
            .AppendLine("#pragma warning disable CS1591")
            .AppendLine()
            .AppendLine("#nullable enable")
            .AppendLine();
    }

    /// <summary>
    /// Appends the standard attributes applied to generated types.
    /// </summary>
    /// <param name="source">The target code builder.</param>
    /// <returns>The same code builder for chaining.</returns>
    public static CodeBuilder AppendGeneratedTypeAttributes(this CodeBuilder source)
    {
        if (source is null)
        {
            throw new ArgumentNullException(nameof(source));
        }

        return source
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Ling.RemoteServices.Generators\", \"")
            .Append(Version)
            .AppendLine("\")]")
            .AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]")
            .AppendLine("[global::System.Diagnostics.DebuggerNonUserCodeAttribute]")
            .AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]");
    }

    public static string TypeName(ITypeSymbol type)
    {
        return type.ToDisplayString(FullyQualifiedNullableFormat);
    }

    public static string RuntimeTypeName(ITypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    public static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    public static string GetGeneratedTypeName(INamedTypeSymbol service, string suffix)
    {
        var serviceName = service.ToDisplayString();
        var safeName = new string(serviceName
            .Select(character => char.IsLetterOrDigit(character) ? character : '_')
            .ToArray());
        return "__" + safeName + "_" + GetDeterministicHash(serviceName) + suffix;
    }

    public static string GetHintName(INamedTypeSymbol service, string suffix)
    {
        var metadataName = service.ToDisplayString();
        var safeName = new string(metadataName
            .Select(character => char.IsLetterOrDigit(character) ? character : '_')
            .ToArray());
        if (safeName.Length > 96)
        {
            safeName = safeName.Substring(safeName.Length - 96);
        }

        return safeName + "." + GetDeterministicHash(metadataName) + "." + suffix + ".g.cs";
    }

    public static string GetRemoteHttpMethodName(string verb)
    {
        return verb switch
        {
            "GET" => "Get",
            "POST" => "Post",
            "PUT" => "Put",
            "PATCH" => "Patch",
            "DELETE" => "Delete",
            _ => throw new InvalidOperationException($"Unsupported HTTP method '{verb}'.")
        };
    }

    private static string GetDeterministicHash(string value)
    {
        const uint offsetBasis = 2166136261;
        const uint prime = 16777619;
        var hash = offsetBasis;

        unchecked
        {
            foreach (var character in value)
            {
                hash ^= character;
                hash *= prime;
            }
        }

        return hash.ToString("X8");
    }

    public static bool IsComplexQuery(ParameterModel parameter)
    {
        return parameter.Kind == BindKind.Query && !ContractParser.IsScalar(parameter.Symbol.Type);
    }

    public static IEnumerable<IPropertySymbol> GetQueryProperties(ParameterModel parameter)
    {
        return ((INamedTypeSymbol)parameter.Symbol.Type).GetMembers()
            .OfType<IPropertySymbol>()
            .Where(property =>
                !property.IsStatic
                && property.GetMethod is not null
                && property.SetMethod is not null);
    }
}
