using Ling.RemoteServices.Client;
using Ling.RemoteServices.Generators.Testing;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.DependencyInjection;

namespace Ling.RemoteServices.Generators.Client.Tests;

public class ClientProxyGeneratorTests
{
    [Fact]
    public void LRS004_reports_when_client_generation_has_no_contracts()
    {
        const string source = "namespace GeneratorFixtures; public sealed class Empty { }";

        var result = CSharpSourceGeneratorVerifier<ClientProxyGenerator>
            .Run(source)
            .GeneratorResult;
        var diagnostic = Assert.Single(
            result.Diagnostics,
            value => value.Id == "LRS004");

        Assert.Equal(DiagnosticSeverity.Warning, diagnostic.Severity);
        Assert.Contains("client generation", diagnostic.GetMessage());
    }

    [Fact]
    public void Generator_emits_one_proxy_file_per_service()
    {
        var run = CSharpSourceGeneratorVerifier<ClientProxyGenerator>.Run(
            GeneratorTestSources.Contracts,
            MetadataReference.CreateFromFile(
                typeof(RemoteServiceClientRuntime).Assembly.Location),
            MetadataReference.CreateFromFile(
                typeof(IServiceCollection).Assembly.Location));
        var result = run.GeneratorResult;
        var hintNames = result.GeneratedSources
            .Select(source => source.HintName)
            .ToArray();

        AssertNoCompilerErrors(run.OutputCompilation);
        Assert.Equal(
            2,
            hintNames.Count(name =>
                name.EndsWith(".ClientProxy.g.cs", StringComparison.Ordinal)));
        Assert.Contains("RemoteServiceClientRegistrationExtensions.g.cs", hintNames);
        Assert.All(result.GeneratedSources, source =>
            AssertGeneratedHeader(source.SourceText.ToString()));
        Assert.All(result.GeneratedSources, source =>
            AssertGeneratedTypeAttributes(source.SourceText.ToString()));

        var registration = GetSource(
            result,
            "RemoteServiceClientRegistrationExtensions.g.cs");
        Assert.Contains(
            "AddScoped<global::GeneratorFixtures.IFirstService",
            registration);
        Assert.Contains(
            "AddScoped<global::GeneratorFixtures.ISecondService",
            registration);

        var firstProxy = result.GeneratedSources
            .Single(source =>
                source.HintName.EndsWith(
                    ".ClientProxy.g.cs",
                    StringComparison.Ordinal)
                && source.SourceText.ToString().Contains(
                    "global::GeneratorFixtures.IFirstService",
                    StringComparison.Ordinal))
            .SourceText
            .ToString();
        Assert.Contains(
            "IRemoteHttpMethodSelectable<global::GeneratorFixtures.IFirstService>",
            firstProxy);
        Assert.Contains(
            "selectedHttpMethod ?? global::Ling.RemoteServices.RemoteHttpMethod.Get",
            firstProxy);
        Assert.Contains("RemoteHttpMethod.Post", firstProxy);
        Assert.Contains(
            "RemoteServiceClientRuntime.GetJsonTypeInfo<string>",
            firstProxy);
        Assert.DoesNotContain(
            "ReadFromJsonAsync<global::System.String>(response.Content, options.JsonSerializerOptions",
            firstProxy);
    }

    private static string GetSource(GeneratorRunResult result, string hintName)
    {
        return Assert.Single(
                result.GeneratedSources,
                source => source.HintName == hintName)
            .SourceText
            .ToString();
    }

    private static void AssertGeneratedHeader(string source)
    {
        var lines = NormalizeLineEndings(source).Split('\n');

        Assert.Equal("// <auto-generated/>", lines[0]);
        Assert.StartsWith("// Generated by Ling.RemoteServices v", lines[1]);
        Assert.EndsWith(".", lines[1]);
        Assert.Equal(string.Empty, lines[2]);
        Assert.Equal("#pragma warning disable CS1591", lines[3]);
        Assert.Equal(string.Empty, lines[4]);
        Assert.Equal("#nullable enable", lines[5]);
        Assert.Equal(string.Empty, lines[6]);
    }

    private static void AssertGeneratedTypeAttributes(string source)
    {
        Assert.Contains("System.CodeDom.Compiler.GeneratedCodeAttribute", source);
        Assert.Contains("System.Runtime.CompilerServices.CompilerGeneratedAttribute", source);
        Assert.Contains("System.Diagnostics.DebuggerNonUserCodeAttribute", source);
        Assert.Contains(
            "System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute",
            source);
    }

    private static string NormalizeLineEndings(string value)
    {
        return value.Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void AssertNoCompilerErrors(Compilation compilation)
    {
        Assert.Empty(compilation.GetDiagnostics().Where(diagnostic =>
            diagnostic.Severity == DiagnosticSeverity.Error));
    }
}
