using Ling.RemoteServices.Generators.Testing;
using Microsoft.CodeAnalysis;

namespace Ling.RemoteServices.Generators.Contract.Tests;

public class ContractGeneratorTests
{
    [Fact]
    public void Generator_preserves_method_summary_in_manifest()
    {
        var run = CSharpSourceGeneratorVerifier<ContractGenerator>
            .Run(GeneratorTestSources.Contracts);
        var manifest = GetSource(
            run.GeneratorResult,
            "RemoteServiceContracts.g.cs");

        AssertNoCompilerErrors(run.OutputCompilation);
        AssertGeneratedHeader(manifest);
        Assert.Contains("RemoteServiceMethodDocumentationAttribute", manifest);
        Assert.Contains("GetAsync\", \"", manifest);
    }

    [Fact]
    public void Generator_does_not_report_contract_diagnostics()
    {
        const string source = """
            using Ling.RemoteServices.Attributes;

            [RemoteService("/api/test")]
            public interface ITestService
            {
                [Get]
                string Get();
            }
            """;

        var result = CSharpSourceGeneratorVerifier<ContractGenerator>
            .Run(source)
            .GeneratorResult;

        Assert.DoesNotContain(result.Diagnostics, diagnostic =>
            diagnostic.Id.StartsWith("LRS", StringComparison.Ordinal));
        Assert.DoesNotContain(result.GeneratedSources, generatedSource =>
            generatedSource.SourceText.ToString().Contains(
                "RemoteServiceContractAttribute",
                StringComparison.Ordinal));
    }

    private static string GetSource(GeneratorRunResult result, string hintName)
    {
        return Assert.Single(
                result.GeneratedSources,
                source => source.HintName == hintName)
            .SourceText
            .ToString();
    }

    private static void AssertGeneratedHeader(string source)
    {
        var lines = source.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');

        Assert.Equal("// <auto-generated/>", lines[0]);
        Assert.StartsWith("// Generated by Ling.RemoteServices v", lines[1]);
        Assert.EndsWith(".", lines[1]);
        Assert.Equal(string.Empty, lines[2]);
        Assert.Equal("#pragma warning disable CS1591", lines[3]);
        Assert.Equal(string.Empty, lines[4]);
        Assert.Equal("#nullable enable", lines[5]);
        Assert.Equal(string.Empty, lines[6]);
    }

    private static void AssertNoCompilerErrors(Compilation compilation)
    {
        Assert.Empty(compilation.GetDiagnostics().Where(diagnostic =>
            diagnostic.Severity == DiagnosticSeverity.Error));
    }
}
