<Project>
  
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix></VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>ling921</Authors>
  </PropertyGroup>
  
</Project>
